books/urls.py
from django.urls import path
from . import views

app_name = 'books'


urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('(?P<book_id>[0-9]+)/', views.detail, name='detail'),
    path('(?P<book_id>[0-9]+)/delete/', views.delete, name='delete'),
    path('create_book/', views.create_book, name='create-book'),
    path('(?P<book_id>[0-9]+)/book/', views.book, name='book'),
    path('(?P<book_id>[0-9]+)/favorite/', views.favorite, name='favorite'),
    path('favorites/', views.favorites, name='favorites'),
]

bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from django.urls import reverse


class Book(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.PROTECT)
    author = models.CharField(max_length=200)
    title = models.CharField(max_length=1000)
    publisher = models.CharField(max_length=500)
    type = models.CharField(max_length=250)
    description = models.TextField(max_length=1000)
    book = models.FileField(default=1)
    cover = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('books:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title + '-' + self.author

books/forms.py
from django import forms
from .models import Book
from django.contrib.auth.models import User


class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('author', 'title', 'publisher', 'type', 'description', 'book', 'cover')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

books/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from . models import Book
from . forms import BookForm, UserForm
from django.db.models import Q


@login_required(login_url='books:login_user')
def index(request):
    books = Book.objects.filter(user=request.user)

    query = request.GET.get("q")
    if query:
        books = books.filter(
            Q(title__icontains=query) |
            Q(author__icontains=query)
        ).distinct()
        return render(request, 'books/index.html', {'books': books})
    else:
        return render(request, 'books/index.html', {'books': books})


@login_required(login_url='books:login_user')
def detail(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'books/details.html', {'book': book})


def delete(request, book_id):
    book = Book.objects.get(pk=book_id)
    book.delete()
    return render(request, 'books/index.html', {'book': book})


@login_required(login_url='books:login_user')
def create_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            book = form.save(commit=False)
            book.user = request.user
            book.cover = request.FILES['cover']
            book.save()
            return render(request, 'books/details.html', {'book': book})
    else:
        form = BookForm()
    return render(request, 'books/create_book.html', {'form': form})


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                books = Book.objects.filter(user=request.user)
                return render(request, 'books/index.html', {'books': books})
    context = {'form': form, }
    return render(request, 'books/register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                books = Book.objects.filter(user=request.user)
                return render(request, 'books/index.html', {'books': books})
            else:
                return render(request, 'books/login.html', {'error_message': 'Your Account is Disabled!'})
        else:
            return render(request, 'books/login.html', {'error_message': 'Invalid Login!'})
    return render(request, 'books/login.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    return render(request, 'books/login.html', {'form': form})


def book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'books/book.html', {'book': book})


def favorite(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    try:
        if book.is_favorite:
            book.is_favorite = False
        else:
            book.is_favorite = True
        book.save()
    except(KeyError, Book.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def favorites(request):
    user = request.user
    books = Book.objects.filter(is_favorite=True)
    return render(request, 'books/favorites.html', {'books': books, 'user': user})

books/templates/books/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}  {% endblock %}</title>

    <!-- Loads static files -->
{% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy">
    <link rel="stylesheet" type="text/css" href="{% static 'books/css/main.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="{% static 'books/js/main.js' %}" type="text/javascript"></script>

</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>

            </button>
            <a class="navbar-brand" href="{% url 'books:index' %}">BookIT</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

             <ul class="nav navbar-nav">
                <li class="{% block books_active %} {% endblock %}"><a href="{% url 'books:index' %}">
                    <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;&nbsp; Books</a></li>

                <li class="{% block favorites_active %} {% endblock %}"><a href="{% url 'books:favorites' %}">
                    <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>&nbsp;&nbsp; Favorites</a></li>

             </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'books:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>

                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                 <li>
                    <a href="{% url 'books:create-book' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp Add Book
                    </a>
                </li>

                <li>
                    <a href="{% url 'books:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %} {% endblock %}
</body>
</html>

books/templates/books/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}BookIT{% endblock %}</title>

        <!-- Loads static files -->
{% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy">
    <link rel="stylesheet" type="text/css" href="{% static 'books/css/main.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'books/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'books:index' %}">BookIT</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'books:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'books:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

books/templates/books/book.html
{% extends 'books/base.html' %}
{% block title %}{{ book.title }}{% endblock %}

{% block body %}
    <div class="container-fluid">
    <div class="row">

        <!-- Left Book info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'books:detail' book.id %}">
                        {% if book.cover %}
                            <img src="{{ book.cover.url }}" class="img-responsive">
                            {% else %}
                            <h3>No image to display.</h3>
                        {% endif %}
                    </a>
                <h2>{{ book.author }}</h2>
                <h3>{{ book.title }}</h3>
                </div>
            </div>
        </div>


    <!-- Right Book Info -->
    <div class="col-sm-8 col-md-9">
        <ul class="nav nav-tabs" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'books:detail' book.id %}">Synopsis</a></li>
                <li role="presentation"><a href="{% url 'books:book' book.id %}">Book</a></li>
            </ul>
        <hr>
        <embed src="{{ book.book.url }}" width="1350px" height="650px" />

    </div>
    </div>
    </div>

{% endblock %}

books/templates/books/create_book.html
{% extends 'books/base.html' %}
{% block title %}Add Book{% endblock %}

{% block body %}
    <div class="container-fluid">
    <div class="row">


        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3 class="text-primary" style="padding-left: 15%;">Add a New Book</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-vertical" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'books/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>


      <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is BookIT?</h3>
                    <p>BookIT is an app that allows you to upload and store all of your books on the cloud.</p>
                    <h3>How do I add books?</h3>
                    <p>First, register by creating a user account. Once you register as a user, you'll be able to log in
                    to your dashboard and add your books.</p>
                    <h3>What are some Book cover best practices?</h3>
                    <ul>
                        <li>Have a resolution of 512x512</li>
                        <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
                        <li>Remain under the 2MB limit.</li>
                        <li>Square images look best</li>
                    </ul>
                </div>
            </div>
        </div>


    </div>
    </div>
{% endblock %}

books/templates/books/details.html
{% extends 'books/base.html' %}
{% load staticfiles %}
<link href="{% static 'books/css/main.css' %}" type="text/css" rel="stylesheet"/>
{% block title %}{{ book.title }}{% endblock %}

{% block body %}
    <div class="container-fluid">
    <div class="row">

        <!-- Left Book info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'books:detail' book.id %}">
                        {% if book.cover %}
                            <img src="{{ book.cover.url }}" class="img-responsive">
                            {% else %}
                            <h3>No image to display.</h3>
                        {% endif %}
                    </a>
                <h2>{{ book.author }}</h2>
                <h3>{{ book.title }}</h3>
                </div>
            </div>
        </div>


    <!-- Right Book Info -->
    <div class="col-sm-8 col-md-9">
        <ul class="nav nav-tabs" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'books:detail' book.id %}">Synopsis</a></li>
                <li role="presentation"><a href="{% url 'books:book' book.id %}">Book</a></li>
            </ul>
        <hr>
        <p style="font-size: 22px;font-family: 'Droid Sans';">{{ book.description }}</p>

    </div>
    </div>
    </div>

{% endblock %}

books/templates/books/favorites.html
{% extends 'books/base.html' %}
{% block title %}Favorites{% endblock %}
{% block favorites_active %}active{% endblock %}

{% block body %}
    <div class="books-container container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <h3 class="text-center text-primary"><strong>{{ request.user }}'s Favorites</strong></h3>
            <hr>
        </div>

        {% if books %}

            {% for book in books %}
                <div class="col-sm-4 col-lg-2">
                <div class="thumbnail">
                    <a href="{% url 'books:detail' book.id %}">
                        <img src="{{ book.cover.url }}" class="img-responsive">
                    </a>

                    <div class="caption">
                        <h2>{{ book.title }}</h2>
                        <h4>{{ book.author }}</h4>

                        <!-- Details -->
                        <a href="{% url 'books:detail' book.id %}" class="btn btn-primary btn-sm" role="button">Details</a>

                        <!-- Delete -->
                    <form action="#" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="book_id" value="{{ book.id }}" />
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>

                        <!-- Favorite Book -->
                    <a href="{% url 'books:favorite' book.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                        <span class="glyphicon glyphicon-star {% if book.is_favorite %}active{% endif %}"></span>
                    </a>
                    </div>
                </div>
                </div>
            {% endfor %}

            {% else %}
           <h4 class="text-center">You Have No Favorites! Kindly, Add your favorite Books.</h4>

        {% endif %}
    </div>
    </div>
{% endblock %}

books/templates/books/form_template.html
{% for field in form %}

    <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>

    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

books/templates/books/index.html
{% extends 'books/base.html' %}
{% block title %}Books{% endblock %}
{% block books_active %}active
{% endblock %}

{% block body %}
    <div class="books-container container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <h3 class="text-center text-primary"><strong>{{ request.user }}'s Books</strong></h3>
            <hr>
        </div>

        {% if books %}

            {% for book in books %}
                <div class="col-sm-3 col-md-3">
                <div class="thumbnail">
                    <a href="{% url 'books:detail' book.id %}">
                        <img src="{{ book.cover.url }}" class="img-responsive">
                    </a>

                    <div class="caption">
                        <h2>{{ book.title }}</h2>
                        <h4>{{ book.author }}</h4>

                        <!-- Details -->
                        <a href="{% url 'books:detail' book.id %}" class="btn btn-primary btn-sm" role="button">Details</a>

                        <!-- Delete -->
                    <form action="#" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="book_id" value="{{ book.id }}" />
                        <button type="submit" class="btn btn-default btn-sm">
                          <a href="{% url 'books:delete' book.id %}"> <span class="glyphicon glyphicon-trash"></span> </a>  
                        </button>
                    </form>

                        <!-- Favorite Book -->
                    <a href="{% url 'books:favorite' book.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                        <span class="glyphicon glyphicon-star {% if book.is_favorite %}active{% endif %}"></span>
                    </a>
                    </div>
                </div>
                </div>
            {% endfor %}

            {% else %}
           <h4 class="text-center">You Have No Books! Kindly, Add your Books.</h4>

        {% endif %}
    </div>
    </div>
{% endblock %}

books/templates/books/login.html
{% extends 'books/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'books:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'books:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>


      <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is BookIT?</h3>
                    <p>BookIT is an app that allows you to upload and store all of your books on the cloud.</p>
                    <h3>How do I add books?</h3>
                    <p>First, register by creating a user account. Once you register as a user, you'll be able to log in
                    to your dashboard and add your books.</p>
                    <h3>What are some Book cover best practices?</h3>
                    <ul>
                        <li>Have a resolution of 512x512</li>
                        <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
                        <li>Remain under the 2MB limit.</li>
                        <li>Square images look best</li>
                    </ul>
                </div>
            </div>
        </div>


    </div>

</div>

{% endblock %}

books/templates/books/register.html
{% extends 'books/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'books/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'books:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>

      <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is BookIT?</h3>
                    <p>BookIT is an app that allows you to upload and store all of your books on the cloud.</p>
                    <h3>How do I add books?</h3>
                    <p>First, register by creating a user account. Once you register as a user, you'll be able to log in
                    to your dashboard and add your books.</p>
                    <h3>What are some Book cover best practices?</h3>
                    <ul>
                        <li>Have a resolution of 512x512</li>
                        <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
                        <li>Remain under the 2MB limit.</li>
                        <li>Square images look best</li>
                    </ul>
                </div>
            </div>
        </div>


    </div>

</div>

{% endblock %}